name: bubbl_flutter_sdk
description: Flutter wrapper for Bubbl SDK v3 native Android and iOS cores.
version: 3.0.1
homepage: https://bubbl.tech
repository: https://devops.bubbl.tech/bubbl/renewed-sdk

environment:
  sdk: ^3.8.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tech.bubbl.flutter_sdk
        pluginClass: BubblFlutterSdkPlugin
      ios:
        pluginClass: BubblFlutterSdkPlugin
